CREATE SCHEMA IF NOT EXISTS xano_mirror;
CREATE TABLE xano_mirror.adpro_usage_backfill (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  invoice_number text NOT NULL,
  artist_name text NOT NULL,
  song_name text NOT NULL
);
CREATE TABLE xano_mirror.agent_conversation (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  owner_user integer NOT NULL DEFAULT 0,
  title text NOT NULL,
  last_message_at timestamptz NOT NULL
);
CREATE TABLE xano_mirror.agent_message (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  conversation integer NOT NULL,
  role text NOT NULL,
  content jsonb NOT NULL
);
CREATE TABLE xano_mirror.ai_prompts (
  id bigint PRIMARY KEY,
  invoice_id integer NOT NULL DEFAULT 0,
  doc_type text NOT NULL,
  file_url text NOT NULL,
  s3_key text NOT NULL,
  file_name text NOT NULL,
  file_size integer NOT NULL DEFAULT 0,
  file_type text NOT NULL,
  uploaded_by integer NOT NULL DEFAULT 0,
  status text NOT NULL,
  uuid uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.brand_category (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  category text NOT NULL
);
CREATE TABLE xano_mirror.briefs (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  one_sentence_brief text NOT NULL,
  audience text NOT NULL,
  audience_to_feel text NOT NULL,
  target_audience text NOT NULL,
  geography_or_time text NOT NULL,
  styles_and_genres text NOT NULL,
  story_or_accents text NOT NULL,
  ref_artist_1 text NOT NULL,
  ref_artist_2 text NOT NULL,
  ref_artist_3 text NOT NULL,
  ref_artist_4 text NOT NULL,
  ref_artist_5 text NOT NULL,
  ref_song_1 text NOT NULL,
  ref_song_2 text NOT NULL,
  ref_song_3 text NOT NULL,
  ref_song_4 text NOT NULL,
  ref_song_5 text NOT NULL,
  ref_link_1 text NOT NULL,
  ref_link_2 text NOT NULL,
  ref_link_3 text NOT NULL,
  ref_link_4 text NOT NULL,
  ref_link_5 text NOT NULL,
  reference_tracks text NOT NULL,
  ref_comments text NOT NULL,
  idea_inspo text NOT NULL,
  off_limits text NOT NULL,
  vocal_or_instrumental text,
  lyrical_themes text NOT NULL,
  anything_else text NOT NULL,
  sequel_deadline text NOT NULL,
  client_deadline date,
  project_master_list_id integer NOT NULL DEFAULT 0,
  brief_type text NOT NULL,
  client_budget_note text NOT NULL,
  client_budget numeric NOT NULL,
  sequel_budget numeric NOT NULL,
  submissions_up_link text NOT NULL,
  uuid uuid,
  share_token text NOT NULL,
  share_expires_at timestamptz,
  status text NOT NULL,
  submitted_at timestamptz,
  requested_by integer,
  source text NOT NULL,
  asset_uuid text NOT NULL
);
CREATE TABLE xano_mirror.client_groups (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  client text NOT NULL
);
CREATE TABLE xano_mirror.client_types (
  id bigint PRIMARY KEY,
  client_type text NOT NULL
);
CREATE TABLE xano_mirror.clients (
  id bigint PRIMARY KEY,
  company text NOT NULL,
  client_type integer NOT NULL DEFAULT 0,
  country integer NOT NULL DEFAULT 0,
  city text NOT NULL,
  region integer NOT NULL,
  street_address text NOT NULL,
  postal_code text NOT NULL,
  invoice_email text NOT NULL,
  accounts_payable_email text NOT NULL,
  uuid uuid,
  status text NOT NULL,
  qbo_customer_id text NOT NULL,
  invoice_instructions text NOT NULL
);
CREATE TABLE xano_mirror.contract_types (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  type text NOT NULL
);
CREATE TABLE xano_mirror.contracts (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  url text NOT NULL,
  description text NOT NULL,
  project_master_list_id integer NOT NULL DEFAULT 0,
  supplier_list_id integer NOT NULL DEFAULT 0,
  contract_type integer NOT NULL DEFAULT 0,
  file_name text NOT NULL,
  aws_path text NOT NULL,
  file_size text NOT NULL,
  file_type text NOT NULL,
  artist text NOT NULL,
  song_name text NOT NULL,
  uploaded_by integer NOT NULL DEFAULT 0,
  confirmed boolean NOT NULL,
  uuid uuid,
  notes text NOT NULL,
  share_code text NOT NULL,
  master_pct numeric,
  publishing_pct numeric,
  mcps_yn boolean NOT NULL,
  status text NOT NULL,
  ai_summary text,
  ai_summary_version text,
  ai_summary_status text,
  start_date date,
  end_date date,
  term_value integer,
  term_unit text,
  perpetual boolean NOT NULL,
  renewal_notify_at date,
  renewal_notified_at timestamptz,
  supplier_address text
);
CREATE TABLE xano_mirror.countries_list (
  id bigint PRIMARY KEY,
  country text NOT NULL
);
CREATE TABLE xano_mirror.creative_links (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  url text NOT NULL,
  added_by integer NOT NULL DEFAULT 0,
  project_master_list_id integer NOT NULL DEFAULT 0
);
CREATE TABLE xano_mirror.currencies_bank_accounts (
  id bigint PRIMARY KEY,
  currency text NOT NULL,
  symbol text,
  created_at timestamptz NOT NULL DEFAULT now(),
  bank_name text NOT NULL,
  account_no text NOT NULL,
  sort_code text NOT NULL,
  iban text NOT NULL,
  bic text NOT NULL,
  intermediary_bic text NOT NULL,
  bank_address text NOT NULL,
  eur_rate numeric NOT NULL DEFAULT 0
);
CREATE TABLE xano_mirror.event_log (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id integer NOT NULL,
  action text NOT NULL,
  metadata jsonb NOT NULL
);
CREATE TABLE xano_mirror.fee_categories (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  prompt_key text NOT NULL,
  prompt_text text NOT NULL,
  prompt_version text NOT NULL
);
CREATE TABLE xano_mirror.fx_rates (
  id bigint PRIMARY KEY,
  base_currency text NOT NULL,
  usd numeric NOT NULL,
  euro numeric NOT NULL,
  jpy numeric NOT NULL,
  sgd numeric NOT NULL,
  gbp numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.image_assets (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  notif_type text NOT NULL,
  message text NOT NULL,
  is_read boolean NOT NULL,
  user_id integer NOT NULL DEFAULT 0,
  song_id integer NOT NULL DEFAULT 0
);
CREATE TABLE xano_mirror.invoice_documents (
  id bigint PRIMARY KEY,
  realm_id text NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  access_expires_at timestamptz NOT NULL,
  refresh_expires_at timestamptz NOT NULL,
  environment text NOT NULL,
  status text NOT NULL,
  last_error text NOT NULL,
  oauth_state text NOT NULL,
  connected_by integer NOT NULL DEFAULT 0,
  connected_at timestamptz NOT NULL,
  last_refreshed_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.invoice_line_items (
  id bigint PRIMARY KEY,
  invoice_id integer NOT NULL DEFAULT 0,
  supplier_id integer NOT NULL DEFAULT 0,
  category text NOT NULL,
  line_type text NOT NULL,
  fee_type text NOT NULL,
  share_percent numeric NOT NULL DEFAULT 0,
  currency integer NOT NULL DEFAULT 0,
  fee_amount numeric NOT NULL DEFAULT 0,
  is_paythrough boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  gbp_amount numeric NOT NULL DEFAULT 0,
  confirmed boolean NOT NULL,
  qbo_bill_id text NOT NULL
);
CREATE TABLE xano_mirror.invoices (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  invoice_number text NOT NULL,
  project_master_list_id integer NOT NULL DEFAULT 0,
  client_id integer NOT NULL DEFAULT 0,
  po_number text NOT NULL,
  po_attachment_url text NOT NULL,
  usage_territories text NOT NULL,
  usage_region text NOT NULL,
  song_name text NOT NULL,
  artist_name text NOT NULL,
  currency_id integer NOT NULL DEFAULT 0,
  demo_contingency_fee numeric NOT NULL DEFAULT 0,
  search_contingency_fee numeric NOT NULL DEFAULT 0,
  license_contingency_fee numeric NOT NULL DEFAULT 0,
  other_contingency_fee numeric NOT NULL DEFAULT 0,
  sequel_demo_fee numeric NOT NULL DEFAULT 0,
  sequel_search_fee numeric NOT NULL DEFAULT 0,
  master_sequel_studios_fee numeric NOT NULL DEFAULT 0,
  master_sequel_licence_fee numeric NOT NULL DEFAULT 0,
  publishing_sequel_studios_fee numeric NOT NULL DEFAULT 0,
  publishing_sequel_licence_fee numeric NOT NULL DEFAULT 0,
  sequel_consultancy_fee numeric NOT NULL DEFAULT 0,
  status text NOT NULL,
  total_to_invoice numeric NOT NULL DEFAULT 0,
  gross_spend numeric NOT NULL DEFAULT 0,
  total_sequel_profit numeric NOT NULL DEFAULT 0,
  aws_link text NOT NULL,
  qbo_invoice_id text NOT NULL,
  exchange_rate_lock numeric NOT NULL DEFAULT 0,
  gbp_total_amount numeric NOT NULL DEFAULT 0,
  description text NOT NULL,
  sp_project_id text NOT NULL,
  file_name text NOT NULL,
  sp_invoice_id text NOT NULL,
  total_local_with_tax integer NOT NULL DEFAULT 0,
  music_supervisor_id integer NOT NULL DEFAULT 0,
  uuid uuid,
  invoice_date date,
  due_date date,
  demo_cost_avoidance numeric NOT NULL DEFAULT 0,
  search_cost_avoidance numeric NOT NULL DEFAULT 0,
  master_cost_avoidance numeric NOT NULL DEFAULT 0,
  publishing_cost_avoidance numeric NOT NULL DEFAULT 0,
  other_cost_avoidance numeric NOT NULL DEFAULT 0,
  eur_rate numeric NOT NULL DEFAULT 0,
  total_third_party_fees numeric NOT NULL DEFAULT 0,
  total_service_fees numeric NOT NULL DEFAULT 0,
  adpro_number text NOT NULL
);
CREATE TABLE xano_mirror.invoices_import (
  id bigint PRIMARY KEY,
  invoice_number integer NOT NULL,
  paythrough_select text NOT NULL,
  client_select text NOT NULL,
  project_type_select text NOT NULL,
  extension text NOT NULL,
  date text NOT NULL,
  region text NOT NULL,
  project_leader text NOT NULL,
  adpro_no text NOT NULL,
  sequel_job_no text NOT NULL,
  brand text NOT NULL,
  product text NOT NULL,
  brand_group text NOT NULL,
  campaign_name text NOT NULL,
  invoicee text NOT NULL,
  invoicee_address text NOT NULL,
  invoicee_country text NOT NULL,
  invoicee_po text NOT NULL,
  invoicee_job_no text NOT NULL,
  invoicee_contact text NOT NULL,
  invoicee_contact_email text NOT NULL,
  big_sync_office_select text NOT NULL,
  currency_select text NOT NULL,
  usage_territory text NOT NULL,
  usage_region text NOT NULL,
  project_originator_staff_member_name text NOT NULL,
  demo_supplier_1_name text NOT NULL,
  demo_supplier_1_fee integer NOT NULL,
  demo_supplier_2_name text NOT NULL,
  demo_supplier_2_fee integer NOT NULL,
  demo_supplier_3_name text NOT NULL,
  demo_supplier_3_fee integer NOT NULL,
  demo_supplier_4_name text NOT NULL,
  demo_supplier_4_fee integer NOT NULL,
  demo_supplier_5_name text NOT NULL,
  demo_supplier_5_fee integer NOT NULL,
  demo_supplier_6_name integer NOT NULL,
  demo_supplier_6_fee integer NOT NULL,
  demo_supplier_7_name integer NOT NULL,
  demo_supplier_7_fee integer NOT NULL,
  demo_supplier_8_name integer NOT NULL,
  demo_supplier_8_fee integer NOT NULL,
  demo_supplier_fees integer NOT NULL,
  cost_avoidance integer NOT NULL,
  sequel_management_fee integer NOT NULL,
  total_demo_fees integer NOT NULL,
  search_supplier_1_name integer NOT NULL,
  search_supplier_1_fee integer NOT NULL,
  search_supplier_2_name integer NOT NULL,
  search_supplier_2_fee integer NOT NULL,
  search_supplier_3_name integer NOT NULL,
  search_supplier_3_fee integer NOT NULL,
  search_supplier_4_name integer NOT NULL,
  search_supplier_4_fee integer NOT NULL,
  search_supplier_5_name integer NOT NULL,
  search_supplier_5_fee integer NOT NULL,
  search_supplier_6_name integer NOT NULL,
  search_supplier_6_fee integer NOT NULL,
  search_supplier_7_name integer NOT NULL,
  search_supplier_7_fee integer NOT NULL,
  search_supplier_8_name integer NOT NULL,
  search_supplier_8_fee integer NOT NULL,
  total_3rd_party_search_fees integer NOT NULL,
  cost_avoidance_manual_input integer NOT NULL,
  sequel_search_fee text NOT NULL,
  total_search_fees text NOT NULL,
  artist_composer text NOT NULL,
  song text NOT NULL,
  usage_territories text NOT NULL,
  initial_cost_m_p text NOT NULL,
  total_master_fee text NOT NULL,
  record_label_1 text NOT NULL,
  record_label_1_share text NOT NULL,
  record_label_1_fee text NOT NULL,
  record_label_2 text NOT NULL,
  record_label_2_share_auto_calculated text NOT NULL,
  record_label_2_fee_auto_calculated text NOT NULL,
  big_sync_creative_share text NOT NULL,
  big_sync_creative_fee integer NOT NULL,
  total_publishing_fee text NOT NULL,
  publisher_1 text NOT NULL,
  publisher_1_share text NOT NULL,
  publisher_1_fee text NOT NULL,
  publisher_2 text NOT NULL,
  publisher_2_share text NOT NULL,
  publisher_2_fee_auto_alculated integer NOT NULL,
  publisher_3 integer NOT NULL,
  publisher_3_share text NOT NULL,
  publisher_3_fee integer NOT NULL,
  publisher_4 text NOT NULL,
  publisher_4_share text NOT NULL,
  publisher_4_fee_auto_calculated integer NOT NULL,
  publisher_5 text NOT NULL,
  publisher_5_share text NOT NULL,
  publisher_5_fee_auto_calculated integer NOT NULL,
  publisher_6 text NOT NULL,
  publisher_6_share text NOT NULL,
  publisher_6_fee_auto_calculated integer NOT NULL,
  sequel_studios text NOT NULL,
  sequel_studios_fee integer NOT NULL,
  share_checker text NOT NULL,
  total_m_p_license_fee_auto_calculated text NOT NULL,
  cost_avoidance_auto_calculated text NOT NULL,
  sequel_license_fee text NOT NULL,
  total_license_fees text NOT NULL,
  paythrough text NOT NULL,
  musicologist integer NOT NULL,
  vat_provision integer NOT NULL,
  other_3rd_party_fees integer NOT NULL,
  "3rd_party_name" integer NOT NULL,
  big_sync_amplification integer NOT NULL,
  sequel_research_strategy integer NOT NULL,
  other_sequel_fees integer NOT NULL,
  total_3rd_party_other_fees_auto_calculated integer NOT NULL,
  cost_avoidance_manual_input_dup2 integer NOT NULL,
  total_big_sync_other_fee integer NOT NULL,
  total_other_fees integer NOT NULL,
  total_third_party_fees text NOT NULL,
  total_cost_avoidance text NOT NULL,
  total_sequel_fees text NOT NULL,
  grand_total text NOT NULL,
  u_invoice_date text NOT NULL,
  business_group text NOT NULL,
  u_category text NOT NULL,
  brand_position text NOT NULL,
  u_brand text NOT NULL,
  u_memo_description text NOT NULL,
  u_type text NOT NULL,
  u_country_job_was_logged text NOT NULL,
  u_usage_territories text NOT NULL,
  u_usage_region text NOT NULL,
  u_adpro_number text NOT NULL,
  u_total_cost_eur text NOT NULL,
  u_total_fees_eur text NOT NULL,
  u_total_3rd_party_fess_eur text NOT NULL,
  u_total_service_fees_eur text NOT NULL,
  u_total_cost_avoidance_eur text NOT NULL,
  u_extension text NOT NULL,
  u_invoice_number text NOT NULL,
  u_date_of_invoice text NOT NULL,
  u_service_jobno text NOT NULL,
  u_invoicee text NOT NULL,
  u_currency text NOT NULL,
  u_rate text NOT NULL,
  u_demo_3rd_party_fees_local_curr text NOT NULL,
  u_demo_3rd_party_supplier_count text NOT NULL,
  u_demo_cost_avoidance_local_curr text NOT NULL,
  u_demo_service_fees_local_curr text NOT NULL,
  u_search_3rd_party_supplier_local_curr text NOT NULL,
  u_search_3rd_party_supplier_count text NOT NULL,
  u_search_cost_avoidance_local_curr text NOT NULL,
  u_search_service_fees_local_curr text NOT NULL,
  u_artist_composer8 text NOT NULL,
  u_song text NOT NULL,
  u_initial_cost_master_pub_local_curr text NOT NULL,
  u_total_master_fee_local_curr text NOT NULL,
  u_total_publishing_fee_local_curr text NOT NULL,
  u_license_3rd_party_fees_local_curr text NOT NULL,
  u_publisher_supplier_count text NOT NULL,
  u_license_cost_avoidance_local_curr text NOT NULL,
  u_license_service_fees_local_curr text NOT NULL,
  u_other_3rd_party_fees_local_curr text NOT NULL,
  u_other_cost_avoidance_local_curr text NOT NULL,
  u_other_service_fees_local_curr text NOT NULL
);
CREATE TABLE xano_mirror.mcps_rate_card (
  id bigint PRIMARY KEY,
  media text NOT NULL,
  territory text NOT NULL,
  per_30s integer NOT NULL,
  track_rate integer NOT NULL,
  campaign_rate integer NOT NULL
);
CREATE TABLE xano_mirror.notifications (
  id bigint PRIMARY KEY,
  category text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  section text NOT NULL
);
CREATE TABLE xano_mirror.project_assets (
  id bigint PRIMARY KEY,
  description text NOT NULL,
  file_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  url text NOT NULL,
  project_master_list_id integer NOT NULL DEFAULT 0,
  uploaded_by integer NOT NULL DEFAULT 0,
  aws_path text,
  file_size text NOT NULL,
  file_type text NOT NULL,
  uuid uuid,
  confirmed boolean NOT NULL,
  final_edit boolean NOT NULL,
  asset_tag text
);
CREATE TABLE xano_mirror.project_master_list (
  id bigint PRIMARY KEY,
  title text NOT NULL,
  uuid uuid NOT NULL,
  created_at text NOT NULL,
  created_at_dup2 date,
  sp_id integer NOT NULL DEFAULT 0,
  sequel_no text NOT NULL,
  brand text NOT NULL,
  sequel_track_link text NOT NULL,
  country text NOT NULL,
  music_supervisor integer NOT NULL DEFAULT 0,
  supe text NOT NULL,
  service_dead text NOT NULL,
  services_id integer NOT NULL DEFAULT 0,
  brand_no text NOT NULL,
  project_status text NOT NULL,
  client_user_id integer NOT NULL DEFAULT 0,
  client_user text NOT NULL,
  project_type text NOT NULL,
  campaignname text NOT NULL,
  adpro_name text NOT NULL,
  project_currency text NOT NULL,
  totalbudget text NOT NULL,
  finaldiscolink text NOT NULL,
  disco_inbox_link text NOT NULL,
  client_project_assets_url text NOT NULL,
  concept text NOT NULL,
  notesorrequest text NOT NULL,
  proposed_start_date text,
  proposed_air_date date,
  project_assets_disco_url text NOT NULL,
  "3rd_party_brief_link" text NOT NULL,
  pipeline_gbp numeric NOT NULL DEFAULT 0,
  webflowid text NOT NULL,
  webflow_url text NOT NULL,
  brand_group text NOT NULL,
  brand_category integer NOT NULL DEFAULT 0,
  product text NOT NULL,
  anyquotessent text NOT NULL,
  anyinvoicessentyn text NOT NULL,
  anycontractssent_yn text NOT NULL,
  schedule_a_status text NOT NULL,
  next_action text NOT NULL,
  closedcancelled_date text NOT NULL,
  confirmed_performing_artist text NOT NULL,
  confirmed_song_name text NOT NULL,
  extension_yn boolean NOT NULL,
  last_contacted text NOT NULL,
  sequel_ownership text NOT NULL,
  sp_form_link text NOT NULL,
  tf_submission_id text NOT NULL,
  winning_composition_team text NOT NULL,
  notes text NOT NULL,
  external_briefing_link text NOT NULL,
  client integer NOT NULL DEFAULT 0,
  confirmed_first_air_date date,
  projects_status integer NOT NULL DEFAULT 1,
  adpro_user integer NOT NULL DEFAULT 142,
  client_agency integer NOT NULL DEFAULT 0,
  library_quote_link text NOT NULL,
  licence_elapse_date date,
  term text NOT NULL,
  territory text NOT NULL,
  media text NOT NULL,
  scripts text NOT NULL,
  durations text NOT NULL,
  cutdowns boolean NOT NULL,
  proposed_artist text NOT NULL,
  proposed_song text NOT NULL,
  cancellation_reason text NOT NULL,
  cancellation_date date,
  status text NOT NULL,
  studio_inbox_link text NOT NULL,
  studio_link text NOT NULL
);
CREATE TABLE xano_mirror.projects_status_options (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  selectable boolean NOT NULL DEFAULT true
);
CREATE TABLE xano_mirror.quickbooks_connection (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  invoice_number text NOT NULL,
  adpro_number text NOT NULL,
  usage_territories text NOT NULL,
  usage_region text NOT NULL
);
CREATE TABLE xano_mirror.quote_line_items (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  quote_id integer NOT NULL DEFAULT 0,
  category text NOT NULL,
  fee_description text NOT NULL,
  cost numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  currencies_bank_accounts_id integer NOT NULL DEFAULT 0,
  services_id integer NOT NULL DEFAULT 0,
  fee_type text NOT NULL
);
CREATE TABLE xano_mirror.quotes (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  music_type text,
  status text NOT NULL,
  artist_name text,
  song_name text,
  term text,
  mcps_territories text,
  media_mcps text[] NOT NULL,
  media text[] NOT NULL,
  online_worldwide boolean,
  scripts text,
  duration text,
  cutdowns_includedyn boolean,
  mcps_track_rate text NOT NULL,
  territory text NOT NULL,
  region text NOT NULL,
  currency text NOT NULL,
  quote_currency integer NOT NULL DEFAULT 0,
  mcps_fee_gbp integer NOT NULL DEFAULT 0,
  sequel_search_fee integer DEFAULT 0,
  searches_requested integer NOT NULL DEFAULT 0,
  total_rights_fee integer DEFAULT 0,
  sequel_licencing_fee integer DEFAULT 0,
  sp_id integer NOT NULL DEFAULT 0,
  wf_id text NOT NULL,
  mcps_local_licence_fee integer NOT NULL DEFAULT 0,
  local_grand_total integer NOT NULL DEFAULT 0,
  note text,
  uuid uuid,
  project_master_list_id integer NOT NULL DEFAULT 0,
  service integer NOT NULL DEFAULT 0,
  description text NOT NULL,
  sequel_production_fee integer NOT NULL,
  sequel_search_quantity integer NOT NULL,
  clients_id integer NOT NULL DEFAULT 0,
  tracks_quoted integer
);
CREATE TABLE xano_mirror.rate_limits (
  id bigint PRIMARY KEY,
  limit_key text NOT NULL,
  hits integer NOT NULL DEFAULT 0,
  window_start timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.region_uplifts (
  id bigint PRIMARY KEY,
  region text NOT NULL,
  percentage numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.regions (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  region text NOT NULL
);
CREATE TABLE xano_mirror.sequel_songs (
  id bigint PRIMARY KEY,
  track_title text NOT NULL,
  composer text NOT NULL,
  supplier_list_id integer NOT NULL DEFAULT 0,
  registration_status text NOT NULL,
  tunecode text NOT NULL,
  project text NOT NULL,
  project_master_list_id integer NOT NULL DEFAULT 0,
  brand text NOT NULL,
  schedule_a_status text NOT NULL,
  ownership text NOT NULL,
  clock_numbers text NOT NULL,
  composer1 text NOT NULL,
  composer1cae text NOT NULL,
  composer1_share text NOT NULL,
  composer2 text NOT NULL,
  composer2cae text NOT NULL,
  composer2_share text NOT NULL,
  composer3 text NOT NULL,
  composer3cae text NOT NULL,
  composer3_share text NOT NULL,
  composer4 text NOT NULL,
  composer4cae text NOT NULL,
  composer_4_share text NOT NULL,
  composer5 text NOT NULL,
  composer5cae text NOT NULL,
  composer5_share text NOT NULL,
  composer6 text NOT NULL,
  composer6cae text NOT NULL,
  composer6_share text NOT NULL,
  composer7 text NOT NULL,
  composer7cae text NOT NULL,
  composer7_share text NOT NULL,
  composer8 text NOT NULL,
  composer8cae text NOT NULL,
  composer8_share text NOT NULL,
  sp_project_id text NOT NULL,
  commencement_date text NOT NULL,
  agreement_number text NOT NULL,
  alternative_titles text NOT NULL,
  campaign_description text NOT NULL,
  script_title text NOT NULL,
  advertising_agency text NOT NULL,
  duration text NOT NULL,
  notes text NOT NULL,
  status text NOT NULL,
  uuid uuid,
  prs_registration_date date,
  commencement_date_dup2 date,
  schedule_a_link text NOT NULL,
  composer_reg_form_status text NOT NULL,
  boldsign_id text NOT NULL
);
CREATE TABLE xano_mirror.sequel_track_invoices (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL,
  collection_id text NOT NULL,
  locale_id text NOT NULL,
  item_id text NOT NULL,
  archived boolean NOT NULL,
  draft boolean NOT NULL,
  created_on text NOT NULL,
  updated_on text NOT NULL,
  published_on text NOT NULL,
  project text NOT NULL,
  invoicee text NOT NULL,
  description text NOT NULL,
  sequel_no text NOT NULL,
  invoice_link text NOT NULL,
  sp_id integer NOT NULL,
  sp_document_id integer NOT NULL
);
CREATE TABLE xano_mirror.sequel_track_quotes_dont_use (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  sp_doc_id integer NOT NULL,
  quote_link text NOT NULL,
  quote_description text NOT NULL,
  track_title text NOT NULL,
  sequel_no text NOT NULL,
  slug text NOT NULL,
  sp_quote_id integer NOT NULL,
  collection_id text NOT NULL,
  locale_id text NOT NULL,
  item_id text NOT NULL,
  project text NOT NULL,
  archived boolean NOT NULL,
  draft boolean NOT NULL,
  created_on text NOT NULL,
  updated_on text NOT NULL,
  published_on text NOT NULL,
  primary_colour text NOT NULL
);
CREATE TABLE xano_mirror.sequel_song_writer (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  song_id integer NOT NULL,
  full_name text NOT NULL,
  cae_number text NOT NULL,
  share_split numeric NOT NULL
);
CREATE TABLE xano_mirror.sequel_writers (
  id bigint PRIMARY KEY,
  writer_uuid uuid NOT NULL,
  cae_number text NOT NULL,
  full_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.services (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  service text NOT NULL
);
CREATE TABLE xano_mirror.short_link (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  short_code text NOT NULL,
  destination_url text NOT NULL,
  expires_at timestamptz NOT NULL
);
CREATE TABLE xano_mirror.song_backfill (
  id bigint PRIMARY KEY,
  limit_key text NOT NULL,
  hits integer NOT NULL DEFAULT 0,
  window_start timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.supplier_list (
  id bigint PRIMARY KEY,
  title text NOT NULL,
  country_to_delete text NOT NULL,
  countries_list_id integer NOT NULL DEFAULT 0,
  vat_registered boolean NOT NULL,
  supplier_type text NOT NULL,
  briefing_list text NOT NULL,
  strengths text NOT NULL,
  approved boolean NOT NULL,
  brief_email text NOT NULL,
  creative_team_member_1_name text NOT NULL,
  creative_team_member_1_email text NOT NULL,
  creative_team_member_2_name text NOT NULL,
  creative_team_member_2_email text NOT NULL,
  creative_team_member_3_name text NOT NULL,
  creative_team_member_3_email text NOT NULL,
  clearance_contact_name_1 text NOT NULL,
  clearance_contact_email_1 text NOT NULL,
  clearance_contact_name_2 text NOT NULL,
  clearance_contact_email_2 text NOT NULL,
  finance_email text NOT NULL,
  regions_id integer NOT NULL DEFAULT 0,
  ca_status text NOT NULL,
  website text NOT NULL,
  access_to_vocalist boolean NOT NULL,
  composition_showreel text NOT NULL,
  sounddesign_showreel text NOT NULL,
  phone_number text NOT NULL,
  stand_out_work text NOT NULL,
  sound_design boolean NOT NULL,
  final_mix boolean NOT NULL,
  final_mix_showreel text NOT NULL,
  composer_library boolean NOT NULL,
  library_link text NOT NULL,
  bio text NOT NULL,
  city text NOT NULL,
  studio_setup text NOT NULL,
  uuid uuid,
  default_currency_id integer NOT NULL DEFAULT 0,
  qbo_vendor_id text NOT NULL,
  revolut_counterparty_id text NOT NULL
);
CREATE TABLE xano_mirror.unilever_commerical_search_fees (
  id bigint PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  region text NOT NULL,
  euro integer NOT NULL,
  gbp integer NOT NULL,
  sgd integer NOT NULL,
  usd integer NOT NULL,
  jpy integer NOT NULL
);
CREATE TABLE xano_mirror.unilever_library_search_fees (
  id bigint PRIMARY KEY,
  region text NOT NULL,
  euro integer NOT NULL,
  gbp integer NOT NULL,
  sgd integer NOT NULL,
  usd integer NOT NULL,
  jpy integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.unilever_minimum_licensing_fees (
  id bigint PRIMARY KEY,
  region text NOT NULL,
  euro integer NOT NULL,
  gbp integer NOT NULL,
  sgd integer NOT NULL,
  usd integer NOT NULL,
  jpy integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.user (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  email text,
  user_type integer NOT NULL DEFAULT 0,
  status integer NOT NULL DEFAULT 0,
  job_title text NOT NULL,
  company_to_archive text NOT NULL,
  company integer NOT NULL DEFAULT 0,
  phone_number text NOT NULL,
  login_code integer NOT NULL DEFAULT 0,
  code_expiry_time timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  uuid uuid,
  notes text NOT NULL,
  finance_user boolean NOT NULL,
  birthday date,
  management boolean NOT NULL
);
CREATE TABLE xano_mirror.user_statuses (
  id bigint PRIMARY KEY,
  status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE xano_mirror.user_types (
  id bigint PRIMARY KEY,
  user_type text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE xano_mirror.agent_message ADD CONSTRAINT agent_message_role_chk CHECK (role IS NULL OR role IN ('system', 'user', 'assistant', 'tool'));
ALTER TABLE xano_mirror.ai_prompts ADD CONSTRAINT ai_prompts_doc_type_chk CHECK (doc_type IS NULL OR doc_type IN ('PO', 'Vendor form', 'Tax form', 'Timesheet', 'Signed quote', 'Other'));
ALTER TABLE xano_mirror.ai_prompts ADD CONSTRAINT ai_prompts_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_vocal_or_instrumental_chk CHECK (vocal_or_instrumental IS NULL OR vocal_or_instrumental IN ('Vocal', 'Instrumental', 'Either'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_brief_type_chk CHECK (brief_type IS NULL OR brief_type IN ('Library', 'Commercial', 'Composition'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_status_chk CHECK (status IS NULL OR status IN ('Requested', 'Submitted', 'Archived'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_source_chk CHECK (source IS NULL OR source IN ('share_link', 'internal', 'upload'));
ALTER TABLE xano_mirror.clients ADD CONSTRAINT clients_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.contracts ADD CONSTRAINT contracts_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.invoice_documents ADD CONSTRAINT invoice_documents_environment_chk CHECK (environment IS NULL OR environment IN ('sandbox', 'production'));
ALTER TABLE xano_mirror.invoice_documents ADD CONSTRAINT invoice_documents_status_chk CHECK (status IS NULL OR status IN ('Connected', 'Disconnected', 'Error'));
ALTER TABLE xano_mirror.invoice_line_items ADD CONSTRAINT invoice_line_items_category_chk CHECK (category IS NULL OR category IN ('Demos', 'Searches', 'Library Master', 'Publishing', 'Other Fees', 'Licence'));
ALTER TABLE xano_mirror.invoice_line_items ADD CONSTRAINT invoice_line_items_line_type_chk CHECK (line_type IS NULL OR line_type IN ('third_party', 'sequel_fee'));
ALTER TABLE xano_mirror.invoice_line_items ADD CONSTRAINT invoice_line_items_fee_type_chk CHECK (fee_type IS NULL OR fee_type IN ('demo', 'search', 'studios', 'licence', 'consultancy', 'contingency', 'in_house'));
ALTER TABLE xano_mirror.invoices ADD CONSTRAINT invoices_usage_region_chk CHECK (usage_region IS NULL OR usage_region IN ('Africa', 'Asia', 'Europe', 'Global', 'Latin America', 'NAMET & RUB', 'North America', 'North Asia', 'SEAA', 'South Asia'));
ALTER TABLE xano_mirror.invoices ADD CONSTRAINT invoices_status_chk CHECK (status IS NULL OR status IN ('Submitted', 'Awaiting Payment', 'Paid', 'Overdue', 'Archived', 'Returned', 'Failed'));
ALTER TABLE xano_mirror.project_assets ADD CONSTRAINT project_assets_asset_tag_chk CHECK (asset_tag IS NULL OR asset_tag IN ('Final edit', 'WIP', 'Deck', 'Reference', 'Other'));
ALTER TABLE xano_mirror.project_master_list ADD CONSTRAINT project_master_list_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.quote_line_items ADD CONSTRAINT quote_line_items_fee_type_chk CHECK (fee_type IS NULL OR fee_type IN ('supplier_cost', 'sequel_fee'));
ALTER TABLE xano_mirror.quotes ADD CONSTRAINT quotes_music_type_chk CHECK (music_type IS NULL OR music_type IN ('Library', 'Commercial', 'Composition'));
ALTER TABLE xano_mirror.quotes ADD CONSTRAINT quotes_status_chk CHECK (status IS NULL OR status IN ('Draft', 'Pending', 'Submitted', 'Approved', 'Archived'));
ALTER TABLE xano_mirror.quotes ADD CONSTRAINT quotes_mcps_track_rate_chk CHECK (mcps_track_rate IS NULL OR mcps_track_rate IN ('Per_30s', 'Track_Rate', 'Campaign_Rate'));
ALTER TABLE xano_mirror.sequel_songs ADD CONSTRAINT sequel_songs_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.supplier_list ADD CONSTRAINT supplier_list_supplier_type_chk CHECK (supplier_type IS NULL OR supplier_type IN ('Agent', 'Manager', 'Publisher', 'Label', 'MCPS Library', 'Non-MCPS Library', 'Sync Rep', 'Composition Team', 'Partner Library', 'Musicologist'));
ALTER TABLE xano_mirror.supplier_list ADD CONSTRAINT supplier_list_briefing_list_chk CHECK (briefing_list IS NULL OR briefing_list IN ('UK', 'Argentina', 'Singapore', 'Global', 'North America'));
ALTER TABLE xano_mirror.supplier_list ADD CONSTRAINT supplier_list_ca_status_chk CHECK (ca_status IS NULL OR ca_status IN ('Not Sent', 'Pending', 'Complete', 'NA'));

