update xano_mirror.agent_conversation set owner_user=null where owner_user=0;
update xano_mirror.agent_message set conversation=null where conversation=0;
update xano_mirror.briefs set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.briefs set requested_by=null where requested_by=0;
update xano_mirror.clients set client_type=null where client_type=0;
update xano_mirror.clients set country=null where country=0;
update xano_mirror.clients set region=null where region=0;
update xano_mirror.contracts set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.contracts set supplier_list_id=null where supplier_list_id=0;
update xano_mirror.contracts set contract_type=null where contract_type=0;
update xano_mirror.contracts set uploaded_by=null where uploaded_by=0;
update xano_mirror.creative_links set added_by=null where added_by=0;
update xano_mirror.creative_links set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.event_log set user_id=null where user_id=0;
update xano_mirror.invoice_documents set invoice_id=null where invoice_id=0;
update xano_mirror.invoice_documents set uploaded_by=null where uploaded_by=0;
update xano_mirror.invoice_line_items set invoice_id=null where invoice_id=0;
update xano_mirror.invoice_line_items set supplier_id=null where supplier_id=0;
update xano_mirror.invoice_line_items set currency=null where currency=0;
update xano_mirror.invoices set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.invoices set client_id=null where client_id=0;
update xano_mirror.invoices set currency_id=null where currency_id=0;
update xano_mirror.invoices set music_supervisor_id=null where music_supervisor_id=0;
update xano_mirror.notifications set user_id=null where user_id=0;
update xano_mirror.notifications set song_id=null where song_id=0;
update xano_mirror.project_assets set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.project_assets set uploaded_by=null where uploaded_by=0;
update xano_mirror.project_master_list set music_supervisor=null where music_supervisor=0;
update xano_mirror.project_master_list set services_id=null where services_id=0;
update xano_mirror.project_master_list set client_user_id=null where client_user_id=0;
update xano_mirror.project_master_list set brand_category=null where brand_category=0;
update xano_mirror.project_master_list set client=null where client=0;
update xano_mirror.project_master_list set projects_status=null where projects_status=0;
update xano_mirror.project_master_list set adpro_user=null where adpro_user=0;
update xano_mirror.project_master_list set client_agency=null where client_agency=0;
update xano_mirror.quickbooks_connection set connected_by=null where connected_by=0;
update xano_mirror.quote_line_items set quote_id=null where quote_id=0;
update xano_mirror.quote_line_items set currencies_bank_accounts_id=null where currencies_bank_accounts_id=0;
update xano_mirror.quote_line_items set services_id=null where services_id=0;
update xano_mirror.quotes set quote_currency=null where quote_currency=0;
update xano_mirror.quotes set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.quotes set service=null where service=0;
update xano_mirror.quotes set clients_id=null where clients_id=0;
update xano_mirror.sequel_songs set supplier_list_id=null where supplier_list_id=0;
update xano_mirror.sequel_songs set project_master_list_id=null where project_master_list_id=0;
update xano_mirror.sequel_song_writer set song_id=null where song_id=0;
update xano_mirror.supplier_list set countries_list_id=null where countries_list_id=0;
update xano_mirror.supplier_list set regions_id=null where regions_id=0;
update xano_mirror.supplier_list set default_currency_id=null where default_currency_id=0;
update xano_mirror.user set user_type=null where user_type=0;
update xano_mirror.user set status=null where status=0;
update xano_mirror.user set company=null where company=0;
alter table xano_mirror.agent_conversation add constraint fk_agent_conversation_owner_user foreign key (owner_user) references xano_mirror.user(id);
alter table xano_mirror.agent_message add constraint fk_agent_message_conversation foreign key (conversation) references xano_mirror.agent_conversation(id);
alter table xano_mirror.briefs add constraint fk_briefs_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id);
alter table xano_mirror.briefs add constraint fk_briefs_requested_by foreign key (requested_by) references xano_mirror.user(id);
alter table xano_mirror.clients add constraint fk_clients_client_type foreign key (client_type) references xano_mirror.client_types(id);
alter table xano_mirror.clients add constraint fk_clients_country foreign key (country) references xano_mirror.countries_list(id);
alter table xano_mirror.clients add constraint fk_clients_region foreign key (region) references xano_mirror.regions(id);
alter table xano_mirror.contracts add constraint fk_contracts_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id);
alter table xano_mirror.contracts add constraint fk_contracts_supplier_list_id foreign key (supplier_list_id) references xano_mirror.supplier_list(id) NOT VALID;
alter table xano_mirror.contracts add constraint fk_contracts_contract_type foreign key (contract_type) references xano_mirror.contract_types(id);
alter table xano_mirror.contracts add constraint fk_contracts_uploaded_by foreign key (uploaded_by) references xano_mirror.user(id);
alter table xano_mirror.creative_links add constraint fk_creative_links_added_by foreign key (added_by) references xano_mirror.user(id);
alter table xano_mirror.creative_links add constraint fk_creative_links_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id);
alter table xano_mirror.event_log add constraint fk_event_log_user_id foreign key (user_id) references xano_mirror.user(id);
alter table xano_mirror.invoice_documents add constraint fk_invoice_documents_invoice_id foreign key (invoice_id) references xano_mirror.invoices(id);
alter table xano_mirror.invoice_documents add constraint fk_invoice_documents_uploaded_by foreign key (uploaded_by) references xano_mirror.user(id);
alter table xano_mirror.invoice_line_items add constraint fk_invoice_line_items_invoice_id foreign key (invoice_id) references xano_mirror.invoices(id) NOT VALID;
alter table xano_mirror.invoice_line_items add constraint fk_invoice_line_items_supplier_id foreign key (supplier_id) references xano_mirror.supplier_list(id) NOT VALID;
alter table xano_mirror.invoice_line_items add constraint fk_invoice_line_items_currency foreign key (currency) references xano_mirror.currencies_bank_accounts(id);
alter table xano_mirror.invoices add constraint fk_invoices_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id);
alter table xano_mirror.invoices add constraint fk_invoices_client_id foreign key (client_id) references xano_mirror.clients(id);
alter table xano_mirror.invoices add constraint fk_invoices_currency_id foreign key (currency_id) references xano_mirror.currencies_bank_accounts(id);
alter table xano_mirror.invoices add constraint fk_invoices_music_supervisor_id foreign key (music_supervisor_id) references xano_mirror.user(id);
alter table xano_mirror.notifications add constraint fk_notifications_user_id foreign key (user_id) references xano_mirror.user(id);
alter table xano_mirror.notifications add constraint fk_notifications_song_id foreign key (song_id) references xano_mirror.sequel_songs(id);
alter table xano_mirror.project_assets add constraint fk_project_assets_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id) NOT VALID;
alter table xano_mirror.project_assets add constraint fk_project_assets_uploaded_by foreign key (uploaded_by) references xano_mirror.user(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_music_supervisor foreign key (music_supervisor) references xano_mirror.user(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_services_id foreign key (services_id) references xano_mirror.services(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_client_user_id foreign key (client_user_id) references xano_mirror.user(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_brand_category foreign key (brand_category) references xano_mirror.brand_category(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_client foreign key (client) references xano_mirror.client_groups(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_projects_status foreign key (projects_status) references xano_mirror.projects_status_options(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_adpro_user foreign key (adpro_user) references xano_mirror.user(id);
alter table xano_mirror.project_master_list add constraint fk_project_master_list_client_agency foreign key (client_agency) references xano_mirror.clients(id);
alter table xano_mirror.quickbooks_connection add constraint fk_quickbooks_connection_connected_by foreign key (connected_by) references xano_mirror.user(id);
alter table xano_mirror.quote_line_items add constraint fk_quote_line_items_quote_id foreign key (quote_id) references xano_mirror.quotes(id) NOT VALID;
alter table xano_mirror.quote_line_items add constraint fk_quote_line_items_currencies_bank_accounts_id foreign key (currencies_bank_accounts_id) references xano_mirror.currencies_bank_accounts(id);
alter table xano_mirror.quote_line_items add constraint fk_quote_line_items_services_id foreign key (services_id) references xano_mirror.services(id);
alter table xano_mirror.quotes add constraint fk_quotes_quote_currency foreign key (quote_currency) references xano_mirror.currencies_bank_accounts(id);
alter table xano_mirror.quotes add constraint fk_quotes_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id) NOT VALID;
alter table xano_mirror.quotes add constraint fk_quotes_service foreign key (service) references xano_mirror.services(id);
alter table xano_mirror.quotes add constraint fk_quotes_clients_id foreign key (clients_id) references xano_mirror.clients(id);
alter table xano_mirror.sequel_songs add constraint fk_sequel_songs_supplier_list_id foreign key (supplier_list_id) references xano_mirror.supplier_list(id);
alter table xano_mirror.sequel_songs add constraint fk_sequel_songs_project_master_list_id foreign key (project_master_list_id) references xano_mirror.project_master_list(id);
alter table xano_mirror.sequel_song_writer add constraint fk_sequel_song_writer_song_id foreign key (song_id) references xano_mirror.sequel_songs(id);
alter table xano_mirror.supplier_list add constraint fk_supplier_list_countries_list_id foreign key (countries_list_id) references xano_mirror.countries_list(id);
alter table xano_mirror.supplier_list add constraint fk_supplier_list_regions_id foreign key (regions_id) references xano_mirror.regions(id);
alter table xano_mirror.supplier_list add constraint fk_supplier_list_default_currency_id foreign key (default_currency_id) references xano_mirror.currencies_bank_accounts(id);
alter table xano_mirror.user add constraint fk_user_user_type foreign key (user_type) references xano_mirror.user_types(id);
alter table xano_mirror.user add constraint fk_user_status foreign key (status) references xano_mirror.user_statuses(id);
alter table xano_mirror.user add constraint fk_user_company foreign key (company) references xano_mirror.clients(id) NOT VALID;

