DROP SCHEMA IF EXISTS xano_mirror CASCADE;
CREATE SCHEMA xano_mirror;
CREATE TABLE xano_mirror.adpro_usage_backfill (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  invoice_number text,
  adpro_number text,
  usage_territories text,
  usage_region text
);
CREATE TABLE xano_mirror.agent_conversation (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  owner_user integer DEFAULT 0,
  title text,
  last_message_at timestamptz
);
CREATE TABLE xano_mirror.agent_message (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  conversation integer,
  role text,
  content jsonb
);
CREATE TABLE xano_mirror.ai_prompts (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  prompt_key text,
  prompt_text text,
  prompt_version text
);
CREATE TABLE xano_mirror.brand_category (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  category text
);
CREATE TABLE xano_mirror.briefs (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name text,
  one_sentence_brief text,
  audience text,
  audience_to_feel text,
  target_audience text,
  geography_or_time text,
  styles_and_genres text,
  story_or_accents text,
  ref_artist_1 text,
  ref_artist_2 text,
  ref_artist_3 text,
  ref_artist_4 text,
  ref_artist_5 text,
  ref_song_1 text,
  ref_song_2 text,
  ref_song_3 text,
  ref_song_4 text,
  ref_song_5 text,
  ref_link_1 text,
  ref_link_2 text,
  ref_link_3 text,
  ref_link_4 text,
  ref_link_5 text,
  reference_tracks text,
  ref_comments text,
  idea_inspo text,
  off_limits text,
  vocal_or_instrumental text,
  lyrical_themes text,
  anything_else text,
  sequel_deadline text,
  client_deadline date,
  project_master_list_id integer DEFAULT 0,
  brief_type text,
  client_budget_note text,
  client_budget numeric,
  sequel_budget numeric,
  submissions_up_link text,
  uuid uuid,
  share_token text,
  share_expires_at timestamptz,
  status text,
  submitted_at timestamptz,
  requested_by integer,
  source text,
  asset_uuid text
);
CREATE TABLE xano_mirror.client_groups (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  client text
);
CREATE TABLE xano_mirror.client_types (
  id bigint PRIMARY KEY,
  client_type text
);
CREATE TABLE xano_mirror.clients (
  id bigint PRIMARY KEY,
  company text,
  client_type integer DEFAULT 0,
  country integer DEFAULT 0,
  city text,
  region integer,
  street_address text,
  postal_code text,
  invoice_email text,
  accounts_payable_email text,
  uuid uuid,
  status text,
  qbo_customer_id text,
  invoice_instructions text
);
CREATE TABLE xano_mirror.contract_types (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  type text
);
CREATE TABLE xano_mirror.contracts (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  url text,
  description text,
  project_master_list_id integer DEFAULT 0,
  supplier_list_id integer DEFAULT 0,
  contract_type integer DEFAULT 0,
  file_name text,
  aws_path text,
  file_size text,
  file_type text,
  artist text,
  song_name text,
  uploaded_by integer DEFAULT 0,
  confirmed boolean,
  uuid uuid,
  notes text,
  share_code text,
  master_pct numeric,
  publishing_pct numeric,
  mcps_yn boolean,
  status text,
  ai_summary text,
  ai_summary_version text,
  ai_summary_status text,
  start_date date,
  end_date date,
  term_value integer,
  term_unit text,
  perpetual boolean,
  renewal_notify_at date,
  renewal_notified_at timestamptz,
  supplier_address text
);
CREATE TABLE xano_mirror.countries_list (
  id bigint PRIMARY KEY,
  country text
);
CREATE TABLE xano_mirror.creative_links (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name text,
  url text,
  added_by integer DEFAULT 0,
  project_master_list_id integer DEFAULT 0
);
CREATE TABLE xano_mirror.currencies_bank_accounts (
  id bigint PRIMARY KEY,
  currency text,
  symbol text,
  created_at timestamptz DEFAULT now(),
  bank_name text,
  account_no text,
  sort_code text,
  iban text,
  bic text,
  intermediary_bic text,
  bank_address text,
  eur_rate numeric DEFAULT 0
);
CREATE TABLE xano_mirror.event_log (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  user_id integer,
  action text,
  metadata jsonb
);
CREATE TABLE xano_mirror.fee_categories (
  id bigint PRIMARY KEY,
  category text,
  sort_order integer DEFAULT 0,
  section text
);
CREATE TABLE xano_mirror.fx_rates (
  id bigint PRIMARY KEY,
  base_currency text,
  usd numeric,
  euro numeric,
  jpy numeric,
  sgd numeric,
  gbp numeric,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.image_assets (
  id uuid PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  image jsonb,
  name text
);
CREATE TABLE xano_mirror.invoice_documents (
  id bigint PRIMARY KEY,
  invoice_id integer DEFAULT 0,
  doc_type text,
  file_url text,
  s3_key text,
  file_name text,
  file_size integer DEFAULT 0,
  file_type text,
  uploaded_by integer DEFAULT 0,
  status text,
  uuid uuid,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.invoice_line_items (
  id bigint PRIMARY KEY,
  invoice_id integer DEFAULT 0,
  supplier_id integer DEFAULT 0,
  category text,
  line_type text,
  fee_type text,
  share_percent numeric DEFAULT 0,
  currency integer DEFAULT 0,
  fee_amount numeric DEFAULT 0,
  is_paythrough boolean,
  created_at timestamptz DEFAULT now(),
  gbp_amount numeric DEFAULT 0,
  confirmed boolean,
  qbo_bill_id text
);
CREATE TABLE xano_mirror.invoices (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  invoice_number text,
  project_master_list_id integer DEFAULT 0,
  client_id integer DEFAULT 0,
  po_number text,
  po_attachment_url text,
  usage_territories text,
  usage_region text,
  song_name text,
  artist_name text,
  currency_id integer DEFAULT 0,
  demo_contingency_fee numeric DEFAULT 0,
  search_contingency_fee numeric DEFAULT 0,
  license_contingency_fee numeric DEFAULT 0,
  other_contingency_fee numeric DEFAULT 0,
  sequel_demo_fee numeric DEFAULT 0,
  sequel_search_fee numeric DEFAULT 0,
  master_sequel_studios_fee numeric DEFAULT 0,
  master_sequel_licence_fee numeric DEFAULT 0,
  publishing_sequel_studios_fee numeric DEFAULT 0,
  publishing_sequel_licence_fee numeric DEFAULT 0,
  sequel_consultancy_fee numeric DEFAULT 0,
  status text,
  total_to_invoice numeric DEFAULT 0,
  gross_spend numeric DEFAULT 0,
  total_sequel_profit numeric DEFAULT 0,
  aws_link text,
  qbo_invoice_id text,
  exchange_rate_lock numeric DEFAULT 0,
  gbp_total_amount numeric DEFAULT 0,
  description text,
  sp_project_id text,
  file_name text,
  sp_invoice_id text,
  total_local_with_tax integer DEFAULT 0,
  music_supervisor_id integer DEFAULT 0,
  uuid uuid,
  invoice_date date,
  due_date date,
  demo_cost_avoidance numeric DEFAULT 0,
  search_cost_avoidance numeric DEFAULT 0,
  master_cost_avoidance numeric DEFAULT 0,
  publishing_cost_avoidance numeric DEFAULT 0,
  other_cost_avoidance numeric DEFAULT 0,
  eur_rate numeric DEFAULT 0,
  total_third_party_fees numeric DEFAULT 0,
  total_service_fees numeric DEFAULT 0,
  adpro_number text
);
CREATE TABLE xano_mirror.invoices_import (
  id bigint PRIMARY KEY,
  invoice_number integer,
  paythrough_select text,
  client_select text,
  project_type_select text,
  extension text,
  date text,
  region text,
  project_leader text,
  adpro_no text,
  sequel_job_no text,
  brand text,
  product text,
  brand_group text,
  campaign_name text,
  invoicee text,
  invoicee_address text,
  invoicee_country text,
  invoicee_po text,
  invoicee_job_no text,
  invoicee_contact text,
  invoicee_contact_email text,
  big_sync_office_select text,
  currency_select text,
  usage_territory text,
  usage_region text,
  project_originator_staff_member_name text,
  demo_supplier_1_name text,
  demo_supplier_1_fee integer,
  demo_supplier_2_name text,
  demo_supplier_2_fee integer,
  demo_supplier_3_name text,
  demo_supplier_3_fee integer,
  demo_supplier_4_name text,
  demo_supplier_4_fee integer,
  demo_supplier_5_name text,
  demo_supplier_5_fee integer,
  demo_supplier_6_name integer,
  demo_supplier_6_fee integer,
  demo_supplier_7_name integer,
  demo_supplier_7_fee integer,
  demo_supplier_8_name integer,
  demo_supplier_8_fee integer,
  demo_supplier_fees integer,
  cost_avoidance integer,
  sequel_management_fee integer,
  total_demo_fees integer,
  search_supplier_1_name integer,
  search_supplier_1_fee integer,
  search_supplier_2_name integer,
  search_supplier_2_fee integer,
  search_supplier_3_name integer,
  search_supplier_3_fee integer,
  search_supplier_4_name integer,
  search_supplier_4_fee integer,
  search_supplier_5_name integer,
  search_supplier_5_fee integer,
  search_supplier_6_name integer,
  search_supplier_6_fee integer,
  search_supplier_7_name integer,
  search_supplier_7_fee integer,
  search_supplier_8_name integer,
  search_supplier_8_fee integer,
  total_3rd_party_search_fees integer,
  cost_avoidance_manual_input integer,
  sequel_search_fee text,
  total_search_fees text,
  artist_composer text,
  song text,
  usage_territories text,
  initial_cost_m_p text,
  total_master_fee text,
  record_label_1 text,
  record_label_1_share text,
  record_label_1_fee text,
  record_label_2 text,
  record_label_2_share_auto_calculated text,
  record_label_2_fee_auto_calculated text,
  big_sync_creative_share text,
  big_sync_creative_fee integer,
  total_publishing_fee text,
  publisher_1 text,
  publisher_1_share text,
  publisher_1_fee text,
  publisher_2 text,
  publisher_2_share text,
  publisher_2_fee_auto_alculated integer,
  publisher_3 integer,
  publisher_3_share text,
  publisher_3_fee integer,
  publisher_4 text,
  publisher_4_share text,
  publisher_4_fee_auto_calculated integer,
  publisher_5 text,
  publisher_5_share text,
  publisher_5_fee_auto_calculated integer,
  publisher_6 text,
  publisher_6_share text,
  publisher_6_fee_auto_calculated integer,
  sequel_studios text,
  sequel_studios_fee integer,
  share_checker text,
  total_m_p_license_fee_auto_calculated text,
  cost_avoidance_auto_calculated text,
  sequel_license_fee text,
  total_license_fees text,
  paythrough text,
  musicologist integer,
  vat_provision integer,
  other_3rd_party_fees integer,
  "3rd_party_name" integer,
  big_sync_amplification integer,
  sequel_research_strategy integer,
  other_sequel_fees integer,
  total_3rd_party_other_fees_auto_calculated integer,
  cost_avoidance_manual_input_dup2 integer,
  total_big_sync_other_fee integer,
  total_other_fees integer,
  total_third_party_fees text,
  total_cost_avoidance text,
  total_sequel_fees text,
  grand_total text,
  u_invoice_date text,
  business_group text,
  u_category text,
  brand_position text,
  u_brand text,
  u_memo_description text,
  u_type text,
  u_country_job_was_logged text,
  u_usage_territories text,
  u_usage_region text,
  u_adpro_number text,
  u_total_cost_eur text,
  u_total_fees_eur text,
  u_total_3rd_party_fess_eur text,
  u_total_service_fees_eur text,
  u_total_cost_avoidance_eur text,
  u_extension text,
  u_invoice_number text,
  u_date_of_invoice text,
  u_service_jobno text,
  u_invoicee text,
  u_currency text,
  u_rate text,
  u_demo_3rd_party_fees_local_curr text,
  u_demo_3rd_party_supplier_count text,
  u_demo_cost_avoidance_local_curr text,
  u_demo_service_fees_local_curr text,
  u_search_3rd_party_supplier_local_curr text,
  u_search_3rd_party_supplier_count text,
  u_search_cost_avoidance_local_curr text,
  u_search_service_fees_local_curr text,
  u_artist_composer8 text,
  u_song text,
  u_initial_cost_master_pub_local_curr text,
  u_total_master_fee_local_curr text,
  u_total_publishing_fee_local_curr text,
  u_license_3rd_party_fees_local_curr text,
  u_publisher_supplier_count text,
  u_license_cost_avoidance_local_curr text,
  u_license_service_fees_local_curr text,
  u_other_3rd_party_fees_local_curr text,
  u_other_cost_avoidance_local_curr text,
  u_other_service_fees_local_curr text
);
CREATE TABLE xano_mirror.mcps_rate_card (
  id bigint PRIMARY KEY,
  media text,
  territory text,
  per_30s integer,
  track_rate integer,
  campaign_rate integer
);
CREATE TABLE xano_mirror.notifications (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  notif_type text,
  message text,
  is_read boolean,
  user_id integer DEFAULT 0,
  song_id integer DEFAULT 0
);
CREATE TABLE xano_mirror.project_assets (
  id bigint PRIMARY KEY,
  description text,
  file_name text,
  created_at timestamptz DEFAULT now(),
  url text,
  project_master_list_id integer DEFAULT 0,
  uploaded_by integer DEFAULT 0,
  aws_path text,
  file_size text,
  file_type text,
  uuid uuid,
  confirmed boolean,
  final_edit boolean,
  asset_tag text
);
CREATE TABLE xano_mirror.project_master_list (
  id bigint PRIMARY KEY,
  title text,
  uuid uuid,
  created_at text,
  created_at_dup2 date,
  sp_id integer DEFAULT 0,
  sequel_no text,
  brand text,
  sequel_track_link text,
  country text,
  music_supervisor integer DEFAULT 0,
  supe text,
  service_dead text,
  services_id integer DEFAULT 0,
  brand_no text,
  project_status text,
  client_user_id integer DEFAULT 0,
  client_user text,
  project_type text,
  campaignname text,
  adpro_name text,
  project_currency text,
  totalbudget text,
  finaldiscolink text,
  disco_inbox_link text,
  client_project_assets_url text,
  concept text,
  notesorrequest text,
  proposed_start_date text,
  proposed_air_date date,
  project_assets_disco_url text,
  "3rd_party_brief_link" text,
  pipeline_gbp numeric DEFAULT 0,
  webflowid text,
  webflow_url text,
  brand_group text,
  brand_category integer DEFAULT 0,
  product text,
  anyquotessent text,
  anyinvoicessentyn text,
  anycontractssent_yn text,
  schedule_a_status text,
  next_action text,
  closedcancelled_date text,
  confirmed_performing_artist text,
  confirmed_song_name text,
  extension_yn boolean,
  last_contacted text,
  sequel_ownership text,
  sp_form_link text,
  tf_submission_id text,
  winning_composition_team text,
  notes text,
  external_briefing_link text,
  client integer DEFAULT 0,
  confirmed_first_air_date date,
  projects_status integer DEFAULT 1,
  adpro_user integer DEFAULT 142,
  client_agency integer DEFAULT 0,
  library_quote_link text,
  licence_elapse_date date,
  term text,
  territory text,
  media text,
  scripts text,
  durations text,
  cutdowns boolean,
  proposed_artist text,
  proposed_song text,
  cancellation_reason text,
  cancellation_date date,
  status text,
  studio_inbox_link text,
  studio_link text
);
CREATE TABLE xano_mirror.projects_status_options (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  status text,
  sort_order integer DEFAULT 0,
  selectable boolean
);
CREATE TABLE xano_mirror.quickbooks_connection (
  id bigint PRIMARY KEY,
  realm_id text,
  access_token text,
  refresh_token text,
  access_expires_at timestamptz,
  refresh_expires_at timestamptz,
  environment text,
  status text,
  last_error text,
  oauth_state text,
  connected_by integer DEFAULT 0,
  connected_at timestamptz,
  last_refreshed_at timestamptz,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.quote_line_items (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  quote_id integer DEFAULT 0,
  category text,
  fee_description text,
  cost numeric DEFAULT 0,
  quantity integer DEFAULT 1,
  currencies_bank_accounts_id integer DEFAULT 0,
  services_id integer DEFAULT 0,
  fee_type text
);
CREATE TABLE xano_mirror.quotes (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  music_type text,
  status text,
  artist_name text,
  song_name text,
  term text,
  mcps_territories text,
  media_mcps text[],
  media text[],
  online_worldwide boolean,
  scripts text,
  duration text,
  cutdowns_includedyn boolean,
  mcps_track_rate text,
  territory text,
  region text,
  currency text,
  quote_currency integer DEFAULT 0,
  mcps_fee_gbp integer DEFAULT 0,
  sequel_search_fee integer DEFAULT 0,
  searches_requested integer DEFAULT 0,
  total_rights_fee integer DEFAULT 0,
  sequel_licencing_fee integer DEFAULT 0,
  sp_id integer DEFAULT 0,
  wf_id text,
  mcps_local_licence_fee integer DEFAULT 0,
  local_grand_total integer DEFAULT 0,
  note text,
  uuid uuid,
  project_master_list_id integer DEFAULT 0,
  service integer DEFAULT 0,
  description text,
  sequel_production_fee integer,
  sequel_search_quantity integer,
  clients_id integer DEFAULT 0,
  tracks_quoted integer
);
CREATE TABLE xano_mirror.rate_limits (
  id bigint PRIMARY KEY,
  limit_key text,
  hits integer DEFAULT 0,
  window_start timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.region_uplifts (
  id bigint PRIMARY KEY,
  region text,
  percentage numeric,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.regions (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  region text
);
CREATE TABLE xano_mirror.sequel_songs (
  id bigint PRIMARY KEY,
  track_title text,
  composer text,
  supplier_list_id integer DEFAULT 0,
  registration_status text,
  tunecode text,
  project text,
  project_master_list_id integer DEFAULT 0,
  brand text,
  schedule_a_status text,
  ownership text,
  clock_numbers text,
  composer1 text,
  composer1cae text,
  composer1_share text,
  composer2 text,
  composer2cae text,
  composer2_share text,
  composer3 text,
  composer3cae text,
  composer3_share text,
  composer4 text,
  composer4cae text,
  composer_4_share text,
  composer5 text,
  composer5cae text,
  composer5_share text,
  composer6 text,
  composer6cae text,
  composer6_share text,
  composer7 text,
  composer7cae text,
  composer7_share text,
  composer8 text,
  composer8cae text,
  composer8_share text,
  sp_project_id text,
  commencement_date text,
  agreement_number text,
  alternative_titles text,
  campaign_description text,
  script_title text,
  advertising_agency text,
  duration text,
  notes text,
  status text,
  uuid uuid,
  prs_registration_date date,
  commencement_date_dup2 date,
  schedule_a_link text,
  composer_reg_form_status text,
  boldsign_id text
);
CREATE TABLE xano_mirror.sequel_track_invoices (
  id bigint PRIMARY KEY,
  name text,
  slug text,
  collection_id text,
  locale_id text,
  item_id text,
  archived boolean,
  draft boolean,
  created_on text,
  updated_on text,
  published_on text,
  project text,
  invoicee text,
  description text,
  sequel_no text,
  invoice_link text,
  sp_id integer,
  sp_document_id integer
);
CREATE TABLE xano_mirror.sequel_track_quotes_dont_use (
  id bigint PRIMARY KEY,
  name text,
  sp_doc_id integer,
  quote_link text,
  quote_description text,
  track_title text,
  sequel_no text,
  slug text,
  sp_quote_id integer,
  collection_id text,
  locale_id text,
  item_id text,
  project text,
  archived boolean,
  draft boolean,
  created_on text,
  updated_on text,
  published_on text,
  primary_colour text
);
CREATE TABLE xano_mirror.sequel_song_writer (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  song_id integer,
  full_name text,
  cae_number text,
  share_split numeric
);
CREATE TABLE xano_mirror.sequel_writers (
  id bigint PRIMARY KEY,
  writer_uuid uuid,
  cae_number text,
  full_name text,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.services (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  service text
);
CREATE TABLE xano_mirror.short_link (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  short_code text,
  destination_url text,
  expires_at timestamptz
);
CREATE TABLE xano_mirror.song_backfill (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  invoice_number text,
  artist_name text,
  song_name text
);
CREATE TABLE xano_mirror.supplier_list (
  id bigint PRIMARY KEY,
  title text,
  country_to_delete text,
  countries_list_id integer DEFAULT 0,
  vat_registered boolean,
  supplier_type text,
  briefing_list text,
  strengths text,
  approved boolean,
  brief_email text,
  creative_team_member_1_name text,
  creative_team_member_1_email text,
  creative_team_member_2_name text,
  creative_team_member_2_email text,
  creative_team_member_3_name text,
  creative_team_member_3_email text,
  clearance_contact_name_1 text,
  clearance_contact_email_1 text,
  clearance_contact_name_2 text,
  clearance_contact_email_2 text,
  finance_email text,
  regions_id integer DEFAULT 0,
  ca_status text,
  website text,
  access_to_vocalist boolean,
  composition_showreel text,
  sounddesign_showreel text,
  phone_number text,
  stand_out_work text,
  sound_design boolean,
  final_mix boolean,
  final_mix_showreel text,
  composer_library boolean,
  library_link text,
  bio text,
  city text,
  studio_setup text,
  uuid uuid,
  default_currency_id integer DEFAULT 0,
  qbo_vendor_id text,
  revolut_counterparty_id text
);
CREATE TABLE xano_mirror.unilever_commerical_search_fees (
  id bigint PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  region text,
  euro integer,
  gbp integer,
  sgd integer,
  usd integer,
  jpy integer
);
CREATE TABLE xano_mirror.unilever_library_search_fees (
  id bigint PRIMARY KEY,
  region text,
  euro integer,
  gbp integer,
  sgd integer,
  usd integer,
  jpy integer,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.unilever_minimum_licensing_fees (
  id bigint PRIMARY KEY,
  region text,
  euro integer,
  gbp integer,
  sgd integer,
  usd integer,
  jpy integer,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.user (
  id bigint PRIMARY KEY,
  name text,
  email text,
  user_type integer DEFAULT 0,
  status integer DEFAULT 0,
  job_title text,
  company_to_archive text,
  company integer DEFAULT 0,
  phone_number text,
  login_code integer DEFAULT 0,
  code_expiry_time timestamptz,
  created_at timestamptz DEFAULT now(),
  uuid uuid,
  notes text,
  finance_user boolean,
  birthday date,
  management boolean
);
CREATE TABLE xano_mirror.user_statuses (
  id bigint PRIMARY KEY,
  status text,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE xano_mirror.user_types (
  id bigint PRIMARY KEY,
  user_type text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE xano_mirror.agent_message ADD CONSTRAINT agent_message_role_chk CHECK (role IS NULL OR role IN ('system', 'user', 'assistant', 'tool'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_vocal_or_instrumental_chk CHECK (vocal_or_instrumental IS NULL OR vocal_or_instrumental IN ('Vocal', 'Instrumental', 'Either'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_brief_type_chk CHECK (brief_type IS NULL OR brief_type IN ('Library', 'Commercial', 'Composition'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_status_chk CHECK (status IS NULL OR status IN ('Requested', 'Submitted', 'Archived'));
ALTER TABLE xano_mirror.briefs ADD CONSTRAINT briefs_source_chk CHECK (source IS NULL OR source IN ('share_link', 'internal', 'upload'));
ALTER TABLE xano_mirror.clients ADD CONSTRAINT clients_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.contracts ADD CONSTRAINT contracts_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.invoice_documents ADD CONSTRAINT invoice_documents_doc_type_chk CHECK (doc_type IS NULL OR doc_type IN ('PO', 'Vendor form', 'Tax form', 'Timesheet', 'Signed quote', 'Other'));
ALTER TABLE xano_mirror.invoice_documents ADD CONSTRAINT invoice_documents_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.invoice_line_items ADD CONSTRAINT invoice_line_items_category_chk CHECK (category IS NULL OR category IN ('Demos', 'Searches', 'Library Master', 'Publishing', 'Other Fees', 'Licence'));
ALTER TABLE xano_mirror.invoice_line_items ADD CONSTRAINT invoice_line_items_line_type_chk CHECK (line_type IS NULL OR line_type IN ('third_party', 'sequel_fee'));
ALTER TABLE xano_mirror.invoice_line_items ADD CONSTRAINT invoice_line_items_fee_type_chk CHECK (fee_type IS NULL OR fee_type IN ('demo', 'search', 'studios', 'licence', 'consultancy', 'contingency', 'in_house'));
ALTER TABLE xano_mirror.invoices ADD CONSTRAINT invoices_usage_region_chk CHECK (usage_region IS NULL OR usage_region IN ('Africa', 'Asia', 'Europe', 'Global', 'Latin America', 'NAMET & RUB', 'North America', 'North Asia', 'SEAA', 'South Asia'));
ALTER TABLE xano_mirror.invoices ADD CONSTRAINT invoices_status_chk CHECK (status IS NULL OR status IN ('Submitted', 'Awaiting Payment', 'Paid', 'Overdue', 'Archived', 'Returned', 'Failed'));
ALTER TABLE xano_mirror.project_assets ADD CONSTRAINT project_assets_asset_tag_chk CHECK (asset_tag IS NULL OR asset_tag IN ('Final edit', 'WIP', 'Deck', 'Reference', 'Other'));
ALTER TABLE xano_mirror.project_master_list ADD CONSTRAINT project_master_list_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.quickbooks_connection ADD CONSTRAINT quickbooks_connection_environment_chk CHECK (environment IS NULL OR environment IN ('sandbox', 'production'));
ALTER TABLE xano_mirror.quickbooks_connection ADD CONSTRAINT quickbooks_connection_status_chk CHECK (status IS NULL OR status IN ('Connected', 'Disconnected', 'Error'));
ALTER TABLE xano_mirror.quote_line_items ADD CONSTRAINT quote_line_items_fee_type_chk CHECK (fee_type IS NULL OR fee_type IN ('supplier_cost', 'sequel_fee'));
ALTER TABLE xano_mirror.quotes ADD CONSTRAINT quotes_music_type_chk CHECK (music_type IS NULL OR music_type IN ('Library', 'Commercial', 'Composition'));
ALTER TABLE xano_mirror.quotes ADD CONSTRAINT quotes_status_chk CHECK (status IS NULL OR status IN ('Draft', 'Pending', 'Submitted', 'Approved', 'Archived'));
ALTER TABLE xano_mirror.quotes ADD CONSTRAINT quotes_mcps_track_rate_chk CHECK (mcps_track_rate IS NULL OR mcps_track_rate IN ('Per_30s', 'Track_Rate', 'Campaign_Rate'));
ALTER TABLE xano_mirror.sequel_songs ADD CONSTRAINT sequel_songs_status_chk CHECK (status IS NULL OR status IN ('Active', 'Archived'));
ALTER TABLE xano_mirror.supplier_list ADD CONSTRAINT supplier_list_supplier_type_chk CHECK (supplier_type IS NULL OR supplier_type IN ('Agent', 'Manager', 'Publisher', 'Label', 'MCPS Library', 'Non-MCPS Library', 'Sync Rep', 'Composition Team', 'Partner Library', 'Musicologist'));
ALTER TABLE xano_mirror.supplier_list ADD CONSTRAINT supplier_list_briefing_list_chk CHECK (briefing_list IS NULL OR briefing_list IN ('UK', 'Argentina', 'Singapore', 'Global', 'North America'));
ALTER TABLE xano_mirror.supplier_list ADD CONSTRAINT supplier_list_ca_status_chk CHECK (ca_status IS NULL OR ca_status IN ('Not Sent', 'Pending', 'Complete', 'NA'));

