// Generated by scripts/strip-licence-template.py — do not hand-edit.
// Measured off the template: x of each value's first character, its
// baseline y in PDF space (from the bottom), Word's character spacing.
export const LIBRARY_LAYOUT = {
  "sequel_no": {
    "page": 0,
    "x": 143.33,
    "y": 468.0,
    "tc": -0.3257,
    "size": 11.04
  },
  "date": {
    "page": 0,
    "x": 138.88,
    "y": 439.44,
    "tc": -0.3146,
    "size": 11.04
  },
  "licensee_name": {
    "page": 0,
    "x": 72.0,
    "y": 339.12,
    "tc": -0.3146,
    "size": 11.04
  },
  "licensee_address": {
    "page": 0,
    "x": 72.0,
    "y": 310.08,
    "tc": -0.3146,
    "size": 11.04
  },
  "binding": {
    "page": 0,
    "x": 72.0,
    "y": 223.68,
    "tc": -0.3191,
    "size": 11.04
  },
  "binding_next": {
    "page": 0,
    "x": 72.0,
    "y": 209.04,
    "tc": -0.3146,
    "size": 11.04
  },
  "rights_granted": {
    "page": 4,
    "x": 136.37,
    "y": 638.4,
    "tc": -0.0155,
    "size": 11.04
  },
  "licensor_share": {
    "page": 4,
    "x": 142.34,
    "y": 613.68,
    "tc": -0.0155,
    "size": 11.04
  },
  "composition_title": {
    "page": 4,
    "x": 96.47,
    "y": 588.96,
    "tc": -0.0144,
    "size": 11.04
  },
  "writer_names": {
    "page": 4,
    "x": 115.27,
    "y": 564.24,
    "tc": -0.1391,
    "size": 11.04
  },
  "production_name": {
    "page": 4,
    "x": 124.67,
    "y": 539.52,
    "tc": -0.0254,
    "size": 11.04
  },
  "client_name": {
    "page": 4,
    "x": 102.32,
    "y": 514.8,
    "tc": -0.0144,
    "size": 11.04
  },
  "brand": {
    "page": 4,
    "x": 102.67,
    "y": 490.32,
    "tc": -0.0254,
    "size": 11.04
  },
  "campaign": {
    "page": 4,
    "x": 120.08,
    "y": 465.6,
    "tc": -0.0144,
    "size": 11.04
  },
  "scripts": {
    "page": 4,
    "x": 107.91,
    "y": 440.88,
    "tc": -0.0254,
    "size": 11.04
  },
  "cutdowns": {
    "page": 4,
    "x": 158.67,
    "y": 416.16,
    "tc": -0.3676,
    "size": 11.04
  },
  "media": {
    "page": 4,
    "x": 103.36,
    "y": 391.44,
    "tc": -0.0254,
    "size": 11.04
  },
  "territory": {
    "page": 4,
    "x": 114.05,
    "y": 366.72,
    "tc": -0.5553,
    "size": 11.04
  },
  "term": {
    "page": 4,
    "x": 98.75,
    "y": 342.24,
    "tc": -0.5553,
    "size": 11.04
  },
  "first_transmission": {
    "page": 4,
    "x": 156.87,
    "y": 317.52,
    "tc": -0.0254,
    "size": 11.04
  },
  "licence_fee": {
    "page": 4,
    "x": 128.13,
    "y": 292.8,
    "tc": -0.0144,
    "size": 11.04
  },
  "after_address": {
    "page": 0,
    "x": 72.0,
    "y": 280.8,
    "tc": -0.3124,
    "size": 11.04
  },
  "page_right": 540
} as const
